---
title: "0 Getting Started with R"
author: "Jeremy Mikecz"
date: "2025-02-24"
output: html_document
---

## 1. Download and Install R and R Studio: https://posit.co/download/rstudio-desktop/

### 1. Download R
    a. Select `Download and Install R`
    b. Select `Download R for {your operating system`
    c. Follow the instructions for downloading and installing R

### 2. Download and Install R Studio
    a. Select `Download Rstudio Desktop for {your operating system}`
	b. Find the installation software you just downloaded (probably in your "Downloads" folder)
    c. Follow instructions for installation

### 3. Folder Setup & Organization
	a. One project, one folder
	b. Folder and file naming
	    i. Keep simple
		ii. Replace whitespace with underscore ("_").
		iii. Add dates for different file versions using iso format: YYYY-MM-DD
			
	c. Subfolders (aka. Subdirectories) for separate components of a project
		i. I.e. research study of spiny anteaters:
		
		```
				spiny_anteaters/
					data/
					field_notes/
					Images/
					notebooks/
					results/
					README.txt
			ii. Or for a class on data visualization
				Dataviz_2026/
					week1/
					week2/
					week3/
					week4/
					week5/
					project/
						code/
						data/
						notes/
						results/
		```
						
### 4. Downloading or Cloning Data from a Repository


#### 4a. Experienced git users only: cloning data


#### 4b. Everyone else: downloading data
	
		
