---
title: "Data Analysis and Visualization with R"
subtitle: "A 2025 Reproducible Research workshop"
author: "Jeremy Mikecz & Steve Gaughan"
institute: "Research Data Services, Dartmouth Libraries"
date: "2026"
format: 
  revealjs:
    theme: night
    navigation-mode: vertical
    chalkboard: true
editor: visual
logo: "../hds_images/logo_white.png"
---

# Data Analysis & Visualization with R  {.scrollable}

Instructors: Jeremy Mikecz & Steve Gaughan\
Research Data Services / Research Facilitation\
Dartmouth Libraries

**A Reproducible Research workshop** (Dartmouth Libraries + Research Computing)

-   details about [this workshop](https://libcal.dartmouth.edu/event/14286329)

-   [view and sign up for other workshops](https://dartgo.org/RRADworkshops)

## This Workshop

-   Download the workshop materials here

-   materials also available on [our Github repository](https://github.com/Dartmouth-Libraries/R-Data-Analysis-and-Visualization)

For additional help or research consultation, you can reach out to ResearchDataHelp\@groups.dartmouth.edu, contact Jeremy & Steve by email, or schedule appoints with us at: [dartgo.org/jeremy](https:dartgo.org/jeremy) and [dartgo.org/steve](https://dartgo.org/steve)

## Goals

## Schedule

::: {.scrollable .incremental}
-   1: Intro to R / R Studio

-   2: Intro to Data Wrangling

-   3: Exploratory Data Viz

-   4: Intro to Stats with R, Part 1

-   Reflection: Takeaways & Questions

-   **Day 2**

-   5: Intro to Stats with R, Part 2

-   6: Mind the Gap: Creating Custom Visualizations

-   7: Geospatial Analysis and Mapping

-   Reflection: Takeaways, Questions, Next Steps, & Feedback
:::

# Day 1

Wednesday, March 19, 2025 (9am - 12:30pm)

Berry Classroom 180a ("The LINK")

# Lesson 1: Intro to R / R Studio

# Lesson 2: Intro to Data Wrangling (tidyverse / dplyr)

## dplyr / tidyverse verbs for data wrangling {.scrollable}

To modify and "wrangle" datasets, the tidyverse commonly uses the following verbs / functions:

-   **select()**: to select specific columns by their names or data types

-   **arrange()**: to order rows by one or more columns

-   **rename()**: to rename columns

-   **mutate()**: to create columns

-   **filter()**: to filter out rows by a given condition

-   **distinct()**: to keep only distinct / unique rows

-   **gather()**: to make "wide" data longer

-   **spread()**: to make "long" data wider

-   **separate()**: to split a single column into multiple columns

-   **unite()**: to combine multiple columns into one

[More tidyverse verbs and functions here](https://dplyr.tidyverse.org/reference/index.html).

# Lesson 3: Exploratory Data Visualization (ggplot)

## GGplot2 resources  {.scrollable}

-   ggplot2 [cheat sheet](https://github.com/rstudio/cheatsheets/blob/main/data-visualization.pdf)

-   ggplot2 library [home page](https://ggplot2.tidyverse.org/) (with links to suggested tutorials / learning materials)

-   ggplot2 book: Wickham, [*ggplot2: Elegant Graphics for Data Analysis*](https://ggplot2-book.org/)(3rd edition).

-   Specific Visualization tutorials:

    -   ggplot2 cookbook: Chang, [*R Graphics Cookbook*](https://r-graphics.org/) *(2024).*

    -   [*R Graph Gallery*](https://r-graph-gallery.com/)

-   ggplot extensions: <https://exts.ggplot2.tidyverse.org/gallery/>

::: important
The [**R Graph Gallery**](https://r-graph-gallery.com/)is a particularly valuable tool for helping you decide what plot type to use for your data and to obtain code for creating such charts.
:::

## The Grammar of Graphics  {.scrollable}

The "gg" in ggplot stands for Grammar of Graphics. GGplot was developed by Hadley Wickham following the Grammar of Graphics model, which.... **\[explain more\]**

-   CU-Boulder Coursera course video on [Grammar of Graphics](https://www.youtube.com/watch?v=RCaFBJWXfZc)

-   Hadley Wickham, ["A Layered Grammar of Graphics"](https://vita.had.co.nz/papers/layered-grammar.html) in *Journal of Computational and Graphical Statistics* (2010).

-   [Cornell course guide](https://info5940.infosci.cornell.edu/notes/dataviz/grammar-of-graphics/)

-   Wickham, [*ggplot2: Elegant Graphics for Data Analysis*](https://ggplot2-book.org/)(3rd edition)

    -   especially Introduction and "The Grammar" chapters (Chapters 13-17)

## "Grammar of Graphics" plots

Plot = Data + Mapping (how data variables are to be visualized)

## ggplot components

data + mapping

mapping = **aesthetic mappings** (link between data and visual variables) + layers (**geom** functions) + scale + coord + facet + theme

sample code:

```         
library(tidyverse)
ggplot(mpg, aes(x = displ, y = hwy)) + 
  geom_point()
```

---

```{r}
library(tidyverse)
ggplot(mpg, aes(x = displ, y = hwy)) + 
  geom_point()
```

---

Five mapping components:

::: incremental
-   layer

-   scale

-   coord

-   facet

-   theme
:::

## layers

includes **geoms** (geometric elements like points, lines, polygons, etc.) and **stats** (statistical transformations that summarize the data, simplifying it for visualization)

## scale

maps data values to visual variables like color, shape, and size

## coord

describes how data will be placed spatially and what coordinate system will be used

## facet

describes how to split data and display it in "small multiples"

## theme

control stylistic choices such as font size and color palettes

# Lesson 4: Intro to Stats with R, Part 1 (dplyr)

# Reflections / Lessons (Day 1)

---

1.  What did you learn today that you are excited to implement in your own work?
2.  Lingering questions

---

1.  Blue post-its: What did we do well / should continue doing?
2.  Pink: what can we do better / differently?

# Day 2

Thursday, March 19, 2025 (9am - 12:30pm)

Berry Classroom 180a ("The LINK")

# Lesson 5: Intro to States with R, Part 2 (dplyr, tidyr, swirl)

# Lesson 6: Mind the Gap: Creating Custom Visualizations (ggplot, plotly)

Begin by watching the famous video of Hans Rosling's Presentation with the Gapminder dataset: ["200 Countries, 200 Years, 4 Minutes"](https://www.youtube.com/watch?v=jbkSRLYSojo).

# Lesson 7: Geospatial Analysis and Mapping

# Workshop - Reflections / Lessons / Feedback

Please let us know what we did well and what we could do better next time. Leave feedback at [dartgo.org/feedback](https://dartgo.org/feedback).
